### ISSUE TITLE
考虑制作一份xray的schema吗？

### ISSUE THREAD

**Issue by ZZYSonny** [cwxyz007/v2ray-config-json-schema#3]
xray目前是v2fly的超集，加入了fullcone nat, xtls这些有意义的功能。

https://github.com/XTLS/Xray-core

https://xtls.github.io/config/

**Comment by cwxyz007** [comment]
> xray目前是v2fly的超集，加入了fullcone nat, xtls这些有意义的功能。
> 
> https://github.com/XTLS/Xray-core
> 
> https://xtls.github.io/config/

简单的看了看，xray 貌似用了和 v2ray-core 一样的配置。这样看来，不需要改什么，直接用就可以了。

如果有一些不同的配置项，我可以在空闲的时候写一份 xray 的 schema。

如果你熟悉 Typescript，也非常欢迎提交 PR。
